# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# characters = Character.create([{name: "Luigi"}, {name: "Mario"}, {name: "DK"}, {name: "Link"}, {name: "Samus"}, {name: "Captain Falcon"}, {name: "Ness"}, {name: "Yoshi"}, {name: "Kirby"}, {name: "Fox"}, {name: "Pikachu"}, {name: "Jigglypuff"}])

# rules = Rule.create([{name: "Preme", description: "Dropping from angel platform before it expires", image: "https://i.imgur.com/ytc6QY2.png"}, {name: "Screen Clear", description: "All players but one are currently dead", image: "https://i.imgur.com/TeSFuDD.jpg"}, {name: "First Blood", description: "Being the first player to die in a new game", image: "https://i.imgur.com/POMLEQu.jpg"}, {name: "Bob-omb Death", description: "Dying from the explosion of a bob-omb", image: "https://i.imgur.com/yecNUmn.png"}, {name: "Bob-omb Miss", description: "Picking up a bob-omb but failing to acquire a kill", image: "https://i.imgur.com/UgaIsq8.png"}, {name: "Pokeball Miss", description: "Picking up a pokeball but failing to open it", image: "https://i.imgur.com/B5nROzX.png"}, {name: "Goldeen", description: "Releasing a goldeen from a pokeball", image: "https://i.imgur.com/W0KXwVw.png"}, {name: "Mew", description: "Releasing Mew from a pokeball", image: "https://i.imgur.com/l8CvJSs.jpg"}, {name: "Home-run Bat", description: "Dying from a home-run bat swing, launched in the direction the tree is facing", image: "https://i.imgur.com/hsDufXr.png"}, {name: "Hammer Death", description: "Dying while holding a hammer", image: "https://i.imgur.com/2K0yAvZ.png"}, {name: "Bumper Death", description: "Dying from a bumper hit", image: "https://i.imgur.com/vtDuI0B.png"}, {name: "Star Kill", description: "Being killed by someone under the effects an invincibility star", image: "https://i.imgur.com/WCW1a96.png"}, {name: "Star Death", description: "Dying while under effects of invincibility star", image: "https://i.imgur.com/D6gr9Ba.jpg"}, {name: "Shield Break", description: "A player's shield is broken", image: "https://i.imgur.com/gH7mRWf.jpg"}, {name: "Crowd Chant KO", description: "Being killed by a player after the audience chants for their character", image: "https://i.imgur.com/z56BCFR.jpg"}, {name: "Healing Death", description: "Being dealt a killing blow while under the effects of a healing item", image: "https://i.imgur.com/8QEqWx4.png"}, {name: "Game Freeze", description: "Causing the game to be freeze or malfunction", image: "https://i.imgur.com/sk6PShu.png"}])

User.last.update(admin: true, password: "admin1234")